"""Record the diamond with Nsight Systems and export that same graph's DOT."""
import json

import torch

from example import prepare, workload
from export_graph import export_structure


@torch.no_grad()
def main():
    buffers, capture_stream, side = prepare()
    y = buffers[-1]
    with torch.cuda.nvtx.range("initialize_nvtx"):
        pass
    runtime = torch.cuda.cudart()
    graph = torch.cuda.CUDAGraph(keep_graph=True)
    graph.enable_debug_mode()

    runtime.cudaProfilerStart()
    with torch.cuda.nvtx.range("capture"):
        with torch.cuda.graph(graph, stream=capture_stream):
            with torch.cuda.nvtx.range("capture/diamond"):
                workload(*buffers, side)
    with torch.cuda.nvtx.range("validate_capture"):
        captured_value = y.cpu()
    with torch.cuda.nvtx.range("instantiate"):
        graph.instantiate()
    with torch.cuda.nvtx.range("first_replay"):
        graph.replay()
        torch.cuda.synchronize()
    with torch.cuda.nvtx.range("replay_warmup"):
        for _ in range(10):
            graph.replay()
        torch.cuda.synchronize()
    with torch.cuda.nvtx.range("ordinary"):
        for iteration in range(3):
            with torch.cuda.nvtx.range(f"ordinary/iteration_{iteration}"):
                workload(*buffers, side)
                torch.cuda.synchronize()
    with torch.cuda.nvtx.range("graph"):
        for iteration in range(3):
            with torch.cuda.nvtx.range(f"graph/iteration_{iteration}"):
                graph.replay()
                torch.cuda.synchronize()
    runtime.cudaProfilerStop()

    final_value = y.cpu()
    assert torch.count_nonzero(captured_value).item() == 0
    assert torch.equal(final_value, torch.full_like(final_value, 31))
    export_structure(graph, buffers, "Same capture and process as profiling/diamond.nsys-rep, generated by profile.py")
    print(json.dumps({"device": torch.cuda.get_device_name(), "torch": torch.__version__,
                      "cuda": torch.version.cuda, "numel": y.numel(), "dtype": str(y.dtype),
                      "kernel_count": 4, "capture_left_output_unchanged": True,
                      "input_value": 7, "final_value": int(final_value[0])}, indent=2))


if __name__ == "__main__":
    main()
